"""Weekly strategic review - every Sunday."""
import json
import os
import time
import requests
from datetime import datetime, timedelta

STATE_DIR = "/root/evo-ai/state/"
DATA_DIR = "/root/evo-ai/data/"
REVIEW_FILE = STATE_DIR + "WEEKLY_LOG.md"

def load_metrics():
    try:
        with open(STATE_DIR + "METRICS.json") as f:
            return json.load(f)
    except:
        return {"metrics": {}}

def analyze_week():
    """Analyze the past week's progress."""
    analysis = {
        "period_start": (datetime.now() - timedelta(days=7)).isoformat(),
        "period_end": datetime.now().isoformat(),
    }
    
    # Evolution progress
    try:
        with open(DATA_DIR + "light_evo_log.jsonl") as f:
            lines = f.readlines()
            if lines:
                # First and last entry
                first = json.loads(lines[0])
                last = json.loads(lines[-1])
                analysis["evolution"] = {
                    "first_generation": first.get("generation", 0),
                    "last_generation": last.get("generation", 0),
                    "first_fitness": first.get("fitness", 0),
                    "last_fitness": last.get("fitness", 0),
                    "generations_added": last.get("generation", 0) - first.get("generation", 0),
                    "fitness_improvement_pct": (
                        (last.get("fitness", 0) - first.get("fitness", 0)) 
                        / max(abs(first.get("fitness", 1)), 0.001) * 100
                    ),
                }
    except:
        analysis["evolution"] = {}
    
    # A2A progress
    try:
        with open(DATA_DIR + "expand_a2a.log") as f:
            content = f.read()
            sent = content.count("Discovered")
            success = content.count("Successful")
            analysis["a2a"] = {
                "batches_sent": sent,
                "batches_successful": success,
            }
    except:
        analysis["a2a"] = {}
    
    # External traffic
    try:
        with open(DATA_DIR + "external_traffic.jsonl") as f:
            lines = f.readlines()
            analysis["traffic"] = {
                "total_entries": len(lines),
                "unique_ips": len(set(lines)),
            }
    except:
        analysis["traffic"] = {}
    
    # Decisions made
    try:
        with open(STATE_DIR + "DECISIONS.md") as f:
            content = f.read()
            analysis["decisions_logged"] = content.count("## ")
    except:
        analysis["decisions_logged"] = 0
    
    return analysis

def generate_review(analysis):
    """Generate human-readable review markdown."""
    md = f"""# Weekly Review - Week Ending {datetime.now().strftime('%Y-%m-%d')}

## Period: {analysis['period_start'][:10]} to {analysis['period_end'][:10]}

## Evolution Progress
"""
    evo = analysis.get("evolution", {})
    if evo:
        md += f"""- Generations: {evo.get('first_generation', '?')} → {evo.get('last_generation', '?')} ({evo.get('generations_added', 0):+d})
- Fitness: {evo.get('first_fitness', 0):.4f} → {evo.get('last_fitness', 0):.4f} ({evo.get('fitness_improvement_pct', 0):+.1f}%)
"""
    else:
        md += "- No evolution data this week\n"
    
    md += f"""
## A2A Outreach
- Batches sent: {analysis.get('a2a', {}).get('batches_sent', 0)}
- Batches successful: {analysis.get('a2a', {}).get('batches_successful', 0)}

## External Traffic
- Total entries: {analysis.get('traffic', {}).get('total_entries', 0)}
- Unique IPs: {analysis.get('traffic', {}).get('unique_ips', 0)}

## Decisions Made This Week
- {analysis.get('decisions_logged', 0)} decisions logged

## Next Week Priorities (Auto-Generated)
"""
    metrics = load_metrics()
    nodes = metrics.get("metrics", {}).get("external_nodes", {}).get("total_registered", 0)
    fitness = metrics.get("metrics", {}).get("model_fitness", {}).get("value", 0)
    ips = metrics.get("metrics", {}).get("external_probes", {}).get("unique_ips", 0)
    
    if nodes < 25:
        md += "- Push harder on real node acquisition (currently " + str(nodes) + ", target 25)\n"
    if fitness < 0.05:
        md += "- Aggressive evolution: fitness " + str(fitness) + " (target 0.05+)\n"
    if ips < 50:
        md += "- Find new external traffic sources (currently " + str(ips) + " unique IPs)\n"
    
    md += """
## Lessons Learned
- (Auto-filled by self_drive based on what worked/failed)

---
*Generated by weekly_review.py on """ + datetime.now().isoformat() + "*\n\n"
    return md

def main():
    print(f"[{datetime.now().isoformat()}] Weekly review starting")
    analysis = analyze_week()
    review = generate_review(analysis)
    
    with open(REVIEW_FILE, "a") as f:
        f.write(review)
    
    print(f"Review written to {REVIEW_FILE}")
    
    # Also publish summary to paste.rs
    try:
        r = requests.post("https://paste.rs/", data=review.encode(), timeout=15)
        url = r.text.strip()
        if url.startswith("https://paste.rs/"):
            print(f"Published: {url}")
    except:
        pass
    
    print(f"[{datetime.now().isoformat()}] Done")

if __name__ == "__main__":
    main()
